#!/bin/bash

TESTS=${TESTS:-1000000}
TIMEFMT='
real    %*E
user    %*U
sys     %*S'

runtest () {
  echo "LP_SHELL_bash=$_LP_SHELL_bash"
  echo -n " LP_SHELL_zsh=$_LP_SHELL_zsh"
  i=0
  while [[ $i -lt $TESTS ]]; do
    _lp_byshell bash zsh > /dev/null
    i=$(( $i+1 ))
  done 
}

if ps -o comm= $$ | grep -q bash; then
  _LP_SHELL_bash=true; _LP_SHELL_zsh=false
  else
  _LP_SHELL_bash=false; _LP_SHELL_zsh=true
fi


for submission in lp_byshell.*; do
  echo "== $submission =="
  source "$PWD/$submission"
  time ( runtest )
  echo;echo
done
