#!/bin/bash

TESTS=${TESTS:-1000000}
TIMEFMT='
real    %*E
user    %*U
sys     %*S'

runtest () {
  echo "LP_SHELL_bash=$_LP_SHELL_bash"
  echo -n " LP_SHELL_zsh=$_LP_SHELL_zsh"
  i=0
  while [[ $i -lt $TESTS ]]; do
    _lp_byshell bash zsh > /dev/null
    i=$(( $i+1 ))
  done 
}

echo "== lp_byshell.1 =="
source $PWD/lp_byshell.1
_LP_SHELL_bash=true; _LP_SHELL_zsh=false
time ( runtest )
echo;echo

_LP_SHELL_bash=false; _LP_SHELL_zsh=true
time ( runtest )
echo;echo

echo "== lp_byshell.2 =="
source $PWD/lp_byshell.2
_LP_SHELL_bash=true; _LP_SHELL_zsh=false
time ( runtest )
echo;echo

_LP_SHELL_bash=false; _LP_SHELL_zsh=true
time ( runtest )
